---
driver:
  name: docker_cli

transport:
  name: docker_cli

provisioner:
  name: wright
  install_method: gems

verifier:
  ruby_bindir: /usr/bin

platforms:
  - name: debian-8.0
    driver_config:
      image: debian:jessie
  - name: ubuntu-15.04
    driver_config:
      image: ubuntu:15.04
  - name: centos-7
    driver_config:
      image: centos:centos7
  - name: fedora-22
    driver_config:
      image: fedora:22

suites:
  - name: default
    wrightfile: lib/wright_include.rb
